name: Main workflow
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        # - macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set Node.js 12.x
      uses: actions/setup-node@v1
      with:
        version: 12.x

    - name: npm install
      run: npm install

    - name: Lint
      run: npm run format-check

    - name: npm test
      run: npm test
